name: Deploy OCR Backend to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'ocr_parser/**'
      - 'requirements.txt'
      - 'vercel.json'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        id: deploy-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel deploy --prod --token=$VERCEL_TOKEN > vercel-deploy-output.txt
          echo "VERCEL_URL=$(cat vercel-deploy-output.txt | tr -d '\n')" >> $GITHUB_OUTPUT
          
      - name: Extract Vercel URL
        id: get-url
        run: |
          VERCEL_URL=$(cat vercel-deploy-output.txt)
          echo "Deployed to: $VERCEL_URL"
          # Clean URL and store it
          CLEAN_URL=$(echo $VERCEL_URL | tr -d '\n')
          echo "BACKEND_URL=$CLEAN_URL" >> $GITHUB_OUTPUT
          
      - name: Update Frontend Deployment Env
        run: |
          echo "Setting OCR_API_URL to ${{ steps.get-url.outputs.BACKEND_URL }} for future frontend deployments"
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/OCR_API_URL \
            -d '{"value":"${{ steps.get-url.outputs.BACKEND_URL }}"}'
